export const streamingServers = {
    AsianLoad: 'asianload',
    BirdStream: 'birdstream',
    BuiltIn: 'builtin',
    DuckStream: 'duckstream',
    Filemoon: 'filemoon',
    GogoCDN: 'gogocdn',
    Luffy: 'luffy',
    MegaCloud: 'megacloud',
    MegaUp: 'megaup',
    MixDrop: 'mixdrop',
    Mp4Upload: 'mp4upload',
    MyCloud: 'mycloud',
    SmashyStream: 'smashystream',
    StreamHub: 'streamhub',
    StreamSB: 'streamsb',
    StreamTape: 'streamtape',
    StreamWish: 'streamwish',
    UpCloud: 'upcloud',
    VidCloud: 'vidcloud',
    VideoStr: 'videostr',
    VidHide: 'vidhide',
    VidMoly: 'vidmoly',
    VidStreaming: 'vidstreaming',
    VizCloud: 'vizcloud',
    Voe: 'voe',
} as const

export type StreamingServers = (typeof streamingServers)[keyof typeof streamingServers]
