name: "✨ Feature Request"
description: Suggest a new idea or improvement for the DreamStream app or packages.
title: "[FEAT] <short summary>"
labels:
  - enhancement
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for helping shape the future of **DreamStream**!

        Tell us what you’d like to see and why it would be useful.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of DreamStream does this feature relate to?
      options:
        - Native app (Expo / React Native)
        - Core package (@dreamstream/core)
        - Extractors (@dreamstream/extractors)
        - Providers (@dreamstream/providers)
        - Monorepo tooling (Turbo, Semantic Release, CI)
        - Documentation
        - Other / Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem or use case would this feature address?
      placeholder: |
        When I try to ..., it’s currently hard because ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your ideal solution or API.
      placeholder: |
        I’d like DreamStream to ...
        A possible API / UX could be ...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you’ve considered
      description: Any workarounds or other approaches you’ve thought about.

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, mockups, or anything else we should know.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and Discussions for a similar request.
          required: true
        - label: I am willing to help with implementation (PRs, testing, feedback).


