name: 'Code Quality Check'
description: 'Fast code quality: lint, format, types, security (Bun optimized)'
author: 'Act-Aks'

inputs:
  fail-on-warnings:
    description: 'Fail on lint warnings'
    required: false
    default: 'false'

outputs:
  all-passed:
    description: 'true if all checks passed'
    value: ${{ steps.quality.outputs.all-passed }}

branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: composite
  steps:
    # All quality checks in one step
    - name: ðŸ” Quality Checks
      id: quality
      shell: bash
      run: |
        echo "ðŸš€ Running quality checks..."
        
        # Linting (fail only on errors unless strict)
        if [[ "${{ inputs.fail-on-warnings }}" == "true" ]]; then
          bun run cq:check || exit 1
        else
          bun run cq:check || echo "âš ï¸ Warnings OK"
        fi
        
        # Formatting check
        bun run cq:fix
        
        # TypeScript
        bun run cq:types
        
        echo "all-passed=true" >> $GITHUB_OUTPUT
        echo "âœ… All checks passed! ðŸš€"
